{
 "title": "Bind9 Full",
 "description": "Bind9 exporter monitoring",
 "tags": [
  "bind",
  "dns"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values(bind_up, instance)"
    }
   },
   {
    "name": "port",
    "label": "port",
    "query": {
     "query": "label_values(bind_up, instance)"
    }
   },
   {
    "name": "view",
    "label": "BIND view",
    "query": {
     "query": "label_values(bind_resolver_query_errors_total, view)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "All DNS Queries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum (rate(bind_incoming_queries_total{instance=\"$host:$port\"}[$__rate_interval]))",
     "legendFormat": "Incoming"
    },
    {
     "expr": "sum (rate(bind_resolver_queries_total{instance=\"$host:$port\"}[$__rate_interval]))",
     "legendFormat": "Outgoing"
    }
   ]
  },
  {
   "title": "Incoming DNS Queries",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(bind_incoming_queries_total{instance=\"$host:$port\"}[$__rate_interval])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Outgoing DNS Queries",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total{instance=\"$host:$port\",view=~\"$view\"}[$__rate_interval])",
     "legendFormat": "{{ type }} {{ view }}"
    }
   ]
  },
  {
   "title": "Incoming Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(bind_incoming_requests_total{instance=\"$host:$port\"}[$__rate_interval])",
     "legendFormat": "{{ opcode }}"
    }
   ]
  },
  {
   "title": "Responses Sent",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(bind_responses_total{instance=\"$host:$port\"}[$__rate_interval])",
     "legendFormat": "{{ result }}"
    }
   ]
  },
  {
   "title": "Last Reconfiguration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "bind_config_time_seconds{instance=\"$host:$port\"} * 1000"
    }
   ]
  },
  {
   "title": "BIND Process Start Time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "bind_boot_time_seconds{instance=\"$host:$port\"} * 1000"
    }
   ]
  },
  {
   "title": "Issues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Resolver Query Retries",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(bind_resolver_query_retries_total{instance=\"$host:$port\",view=~\"$view\"}[$__rate_interval])",
       "legendFormat": "queries retry {{ view }}"
      }
     ]
    },
    {
     "title": "Query Issues",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(bind_query_duplicates_total{instance=\"$host:$port\"}[$__rate_interval])",
       "legendFormat": "Duplicated queries received"
      },
      {
       "expr": "rate(bind_query_errors_total{instance=\"$host:$port\"}[$__rate_interval])",
       "legendFormat": "{{ error }} queries"
      },
      {
       "expr": "rate(bind_query_recursions_total{instance=\"$host:$port\"}[$__rate_interval])",
       "legendFormat": "Queries causing recursions"
      }
     ]
    },
    {
     "title": "Resolver Response Errors Received",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(bind_resolver_response_errors_total{instance=\"$host:$port\",view=~\"$view\"}[$__rate_interval])",
       "legendFormat": "{{ error }} {{ view }}"
      }
     ]
    },
    {
     "title": "Resolver Queries Failed",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(bind_resolver_query_errors_total{instance=\"$host:$port\",view=~\"$view\"}[$__rate_interval])",
       "legendFormat": "{{ error }} {{ view }}"
      },
      {
       "expr": "rate(bind_resolver_query_edns0_errors_total{instance=\"$host:$port\",view=~\"$view\"}[$__rate_interval])",
       "legendFormat": "EDNS(0) error {{ view }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Resolver Query round-trip Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(bind_resolver_query_duration_seconds_bucket{instance=\"$host:$port\",view=~\"$view\"}[$__rate_interval])",
       "legendFormat": "{{ le }} round-trip {{ view }}"
      }
     ]
    },
    {
     "title": "Resolver Query round-trip Count",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(bind_resolver_query_duration_seconds_count{instance=\"$host:$port\",view=~\"$view\"}[$__rate_interval])",
       "legendFormat": "count {{ view }}"
      }
     ]
    },
    {
     "title": "RRSets in Cache Database",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "bind_resolver_cache_rrsets{instance=\"$host:$port\",view=~\"$view\"}",
       "legendFormat": "{{ type }} {{ view }}"
      }
     ]
    },
    {
     "title": "Responses Received Truncated / Mismatch / Lame",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(bind_resolver_response_truncated_total{instance=\"$host:$port\",view=~\"$view\"}[$__rate_interval])",
       "legendFormat": "truncated {{ view }}"
      },
      {
       "expr": "rate(bind_resolver_response_mismatch_total{instance=\"$host:$port\",view=~\"$view\"}[$__rate_interval])",
       "legendFormat": "mismatch {{ view }}"
      },
      {
       "expr": "rate(bind_resolver_response_lame_total{instance=\"$host:$port\",view=~\"$view\"}[$__rate_interval])",
       "legendFormat": "lame {{ view }}"
      }
     ]
    },
    {
     "title": "Recursive Clients",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "bind_recursive_clients{instance=\"$host:$port\"}",
       "legendFormat": "Recursive clients"
      }
     ]
    },
    {
     "title": "Response RCODEs",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(bind_response_rcodes_total{instance=\"$host:$port\"}[$__rate_interval])",
       "legendFormat": "{{ rcode }}"
      }
     ]
    },
    {
     "title": "Tasks Running / Worker Threads",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "bind_tasks_running{instance=\"$host:$port\"}",
       "legendFormat": "Tasks running"
      },
      {
       "expr": "bind_worker_threads{instance=\"$host:$port\"}",
       "legendFormat": "Worker threads"
      }
     ]
    },
    {
     "title": "Response Policy Zone Rewrites",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(bind_response_policy_zone_rewrites_total{instance=\"$host:$port\"}[$__rate_interval])",
       "legendFormat": "RPZ rewrites"
      }
     ]
    },
    {
     "title": "Zone Transfers",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(bind_zone_transfer_success_total{instance=\"$host:$port\"}[$__rate_interval])",
       "legendFormat": "Success"
      },
      {
       "expr": "rate(bind_zone_transfer_failure_total{instance=\"$host:$port\"}[$__rate_interval])",
       "legendFormat": "Failure"
      },
      {
       "expr": "rate(bind_zone_transfer_rejected_total{instance=\"$host:$port\"}[$__rate_interval])",
       "legendFormat": "Rejected"
      }
     ]
    }
   ]
  },
  {
   "title": "DNSsec",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "DNSSEC Validation Attempts",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(bind_resolver_dnssec_validation_errors_total{instance=\"$host:$port\",view=~\"$view\"}[$__rate_interval])",
       "legendFormat": "Errors {{ view }}"
      },
      {
       "expr": "sum by (instance, view)(rate(bind_resolver_dnssec_validation_success_total{instance=\"$host:$port\",view=~\"$view\"}[$__rate_interval]))",
       "legendFormat": "Success {{ view }}"
      }
     ]
    }
   ]
  }
 ]
}